### PR TITLE
handle errors consistently

### LINKED ISSUE #13: each program should exit with appropriate exit code
If one of the file system operations fails, a program should exit with an exit code of 1. Some of the implementations do this; others do not.

### PR DESCRIPTION
**Pull request by davidchambers**
Closes #13

Thanks for this suggestion, @raine! Handling the error cases makes the examples more realistic.

Interestingly, __await.js__ loses any appeal it may once have had.

### CODE REVIEW

File: await.js [hunk 1]
```diff
@@ -21,11 +21,23 @@ const readFile = (options, filename) =>
...
 async function main() {
   const index = path.join(process.argv[2], 'index.txt');
-  const data = await readFile({encoding: 'utf8'}, index);
+  let data;
+  try {
+    data = await readFile({encoding: 'utf8'}, index);
+  } catch (err) {
+    process.stderr.write(String(err) + '\n');
+    process.exit(1);
+  }
```
Comment (benperez) [inline await.js]: If you omit the `try/catch` won't this result in an uncaught exception that crashes the program with a non-zero exit code?

File: coroutines-bluebird.js [hunk 2]
```diff
@@ -29,8 +29,14 @@ const walk = bluebird.coroutine(function*(dir) {
...
-    .catch(s => process.stderr.write(s))
-    .then(s => process.stdout.write(s));
+  .then(data => {
+          process.stdout.write(data);
+          process.exit(0);
+        },
+        err => {
+          process.stderr.write(String(err) + '\n');
+          process.exit(1);
+        });
```
Comment (benperez) [inline coroutines-bluebird.js]: This might be better written as
```javascript
.then(data => {})
.catch(err => {})
```

Comment (davidchambers) [inline coroutines-bluebird.js]: What's the advantage of one approach over the other?

File: await.js (hunk 1 above)
Comment (davidchambers) [inline await.js]: One would think so! In fact, the program exits immediately with an exit code of 0, without writing anything to stdout or to stderr:

```console
$ node --harmony await.compiled.js input
FOO
BAR
BAZ

$ node --harmony await.compiled.js XXX

$ echo $?
0
```

This may be a bug in Babel, I don't know.

File: coroutines-bluebird.js (hunk 2 above)
Comment (benperez) [inline coroutines-bluebird.js]: In the following snippet if the then clause throws an error it will be silently rejected
```javascript
.then(data => {"something with data"}, err => {"something with err"});
```
In this version it will show up in the `catch`
```javascript
.then(data => {"something with data"})
.catch(err => {"something with err"})
```

Comment (davidchambers) [inline coroutines-bluebird.js]: The success handler should not throw in this case.

Providing two functions to `.then` highlights a similarity between Promise and Task.
